/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 20-oct.-2021 12:59:04 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Campus` CASCADE
;

DROP TABLE IF EXISTS `invoice` CASCADE
;

DROP TABLE IF EXISTS `invoice_detail` CASCADE
;

DROP TABLE IF EXISTS `User` CASCADE
;

DROP TABLE IF EXISTS `Vehicle` CASCADE
;

DROP TABLE IF EXISTS `vehicle_detail` CASCADE
;

DROP TABLE IF EXISTS `vehicle_type` CASCADE
;

/* Create Tables */

CREATE TABLE `Campus`
(
	`id_campus` INT NOT NULL AUTO_INCREMENT,
	`name_campus` VARCHAR(20) NOT NULL,
	`address` VARCHAR(40) NOT NULL,
	CONSTRAINT `PK_Campus` PRIMARY KEY (`id_campus` ASC)
)

;

CREATE TABLE `invoice`
(
	`id_invoice` INT NOT NULL AUTO_INCREMENT,
	`VAT` DOUBLE(10,2) NOT NULL,
	`payment_method` VARCHAR(50) NOT NULL,
	`date` DATE NOT NULL,
	`id_campus` INT NULL,
	`id_user` INT NULL,
	CONSTRAINT `PK_invoice` PRIMARY KEY (`id_invoice` ASC)
)

;

CREATE TABLE `invoice_detail`
(
	`id_invoice_det` INT NOT NULL AUTO_INCREMENT,
	`amount` INT NOT NULL,
	`id_invoice` INT NULL,
	`price` DOUBLE(10,2) NULL,
	`id_vehicle_detail` INT NULL,
	CONSTRAINT `PK_invoice_detail` PRIMARY KEY (`id_invoice_det` ASC)
)

;

CREATE TABLE `User`
(
	`id_user` INT NOT NULL AUTO_INCREMENT,
	`user_name1` VARCHAR(20) NOT NULL,
	`user_name2` VARCHAR(20) NULL,
	`user_lastname1` VARCHAR(20) NULL,
	`user_lastname2` VARCHAR(20) NULL,
	`user_email` VARCHAR(40) NULL,
	`user_phone` VARCHAR(20) NULL,
	CONSTRAINT `PK_User` PRIMARY KEY (`id_user` ASC)
)

;

CREATE TABLE `Vehicle`
(
	`id_vehicle` INT NOT NULL AUTO_INCREMENT,
	`color` VARCHAR(50) NOT NULL,
	`description` TEXT NOT NULL,
	`brand` VARCHAR(50) NOT NULL,
	`url` TEXT NOT NULL,
	`id_vehicle_type` INT NOT NULL,
	CONSTRAINT `PK_Vehicle` PRIMARY KEY (`id_vehicle` ASC)
)

;

CREATE TABLE `vehicle_detail`
(
	`id_vehicle_detail` INT NOT NULL AUTO_INCREMENT,
	`car_plate` VARCHAR(10) NOT NULL,
	`engine_num` VARCHAR(50) NOT NULL,
	`chassis_num` VARCHAR(50) NOT NULL,
	`id_vehicle` INT NULL,
	CONSTRAINT `PK_Table3` PRIMARY KEY (`id_vehicle_detail` ASC)
)

;

CREATE TABLE `vehicle_type`
(
	`id_vehicle_type` INT NOT NULL AUTO_INCREMENT,
	`body_type` VARCHAR(50) NOT NULL,
	`description` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_vehicle_type` PRIMARY KEY (`id_vehicle_type` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `invoice` 
 ADD INDEX `IXFK_invoice_Campus` (`id_campus` ASC)
;

ALTER TABLE `invoice` 
 ADD INDEX `IXFK_invoice_User` (`id_user` ASC)
;

ALTER TABLE `invoice_detail` 
 ADD INDEX `IXFK_invoice_detail_invoice` (`id_invoice` ASC)
;

ALTER TABLE `invoice_detail` 
 ADD INDEX `IXFK_invoice_detail_vehicle_detail` (`id_vehicle_detail` ASC)
;

ALTER TABLE `Vehicle` 
 ADD INDEX `IXFK_Vehicle_vehicle_type` (`id_vehicle_type` ASC)
;

ALTER TABLE `vehicle_detail` 
 ADD INDEX `IXFK_vehicle_detail_Vehicle` (`id_vehicle` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `invoice_detail` 
 ADD CONSTRAINT `FK_invoice_detail_vehicle_detail`
	FOREIGN KEY (`id_vehicle_detail`) REFERENCES `vehicle_detail` (`id_vehicle_detail`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Vehicle` 
 ADD CONSTRAINT `FK_Vehicle_vehicle_type`
	FOREIGN KEY (`id_vehicle_type`) REFERENCES `vehicle_type` (`id_vehicle_type`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `vehicle_detail` 
 ADD CONSTRAINT `FK_vehicle_detail_Vehicle`
	FOREIGN KEY (`id_vehicle`) REFERENCES `Vehicle` (`id_vehicle`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
